services:
  postgres:
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=Asia/Kolkata


    ports:
      - '5432:5432'




